"""Exporting one approved report into the vault — deterministically, on request.

**Only ``immutable`` reports export** (section 2.8, rule 1): a draft was never agreed to
and a rejected run was declined, so neither may leave a trace in the vault. Nothing
exports automatically; the report page and the CLI both call this, and both only when a
person asked.

**A second export is the first export.** Every note is a function of the database state
and the reports' own approval dates — no wall clock reaches a byte — so re-exporting an
unchanged report rewrites identical files. What changes between exports is only the
``obsidian_exports`` row recording the act.

**Every link the export writes resolves.** The export covers the connected component of
the competitor *and theme* relations around the subject (see :mod:`aer.obsidian.graph`):
run and source notes for every approved run of every company in it, a company note for
each — a stub, honestly labelled, where a company was named as a comparable but never
researched — plus the catalyst, industry and theme notes those runs' notes point at.
Closure is what makes the vault a journal rather than a folder of exports.
"""

from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime
from typing import Any

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from aer.config import Settings
from aer.core.enums import ClaimKind
from aer.core.sectors import SectorProfile
from aer.db.models import (
    Claim,
    Company,
    Job,
    ObsidianExport,
    Report,
    ReportSection,
    ResearchRequest,
    SectionDefinition,
    SourceDocument,
)
from aer.errors import AerError
from aer.obsidian.graph import CompanyView, LinkGraph, RunView, ThemeView, build_graph
from aer.obsidian.notes import (
    CatalystNoteMeta,
    CompanyNoteMeta,
    IndustryNoteMeta,
    RunNoteMeta,
    SourceNoteMeta,
    ThemeNoteMeta,
    render_note,
)
from aer.obsidian.vault import VaultWriter
from aer.services.history import report_view
from aer.version import version

__all__ = ["ObsidianExportError", "export_report"]

_log = structlog.get_logger("aer.obsidian.export")

# What may appear in a filename. Everything else becomes a hyphen: vault filenames come
# partly from fetched document titles, and a title is data, not a path.
_UNSAFE = re.compile(r"[^A-Za-z0-9 \-_.,()&]")

_README = """# Generated by Tracework Invest

Everything in this vault outside `99-Personal/` is machine-generated from approved
research runs. The database and the artefact store remain the record; these notes are a
derived, one-directional projection of them.

- Notes are regenerated on export. In evergreen notes (companies, industries, MOC), only
  the content **above** the `AER:END-GENERATED` marker is rewritten; anything you write
  below a marker is yours and survives every regeneration.
- `99-Personal/` is never written by the application.
- Prior research informs hypotheses only. It is never evidence: a claim reused from an
  earlier note must be re-sourced before it can support anything.

This is a personal research tool. Nothing in this vault is regulated investment advice.
"""


class ObsidianExportError(AerError):
    """The report may not export, or the vault is not configured."""

    code = "obsidian_export_refused"


async def export_report(
    session: AsyncSession, *, settings: Settings, report_id: uuid.UUID
) -> ObsidianExport:
    """Project one approved report — and its link neighbourhood — into the vault.

    Raises:
        ObsidianExportError: If no vault root is configured, or the report does not
            exist, or it was never approved — rule 1 is checked here, before any path
            is even resolved.
    """
    if settings.obsidian_vault_root is None:
        message = "No Obsidian vault is configured (AER_OBSIDIAN_VAULT_ROOT). Nothing was written."
        raise ObsidianExportError(message)

    report = await session.get(Report, report_id)
    if report is None:
        message = f"No report {report_id}."
        raise ObsidianExportError(message, context={"report_id": str(report_id)})
    if not report.immutable or report.approved_at is None:
        message = (
            "Only approved reports export. This report was never approved, and a draft "
            "must not leave a trace in the vault (section 2.8, rule 1)."
        )
        raise ObsidianExportError(message, context={"report_id": str(report_id)})

    request = await session.get(ResearchRequest, report.request_id)
    job = await session.get(Job, report.job_id)
    if request is None or job is None:  # pragma: no cover -- FK-guaranteed rows
        message = f"Report {report_id} has lost its request or job."
        raise ObsidianExportError(message, context={"report_id": str(report_id)})
    company = (
        await session.get(Company, report.company_id) if report.company_id is not None else None
    )
    company_name = company.name if company is not None else request.company_name

    writer = VaultWriter(
        settings.obsidian_vault_root, personal_root=settings.obsidian_personal_root
    )

    stamp = report.approved_at.astimezone(UTC)
    generator = f"tracework-aer@{version()}"
    graph = await build_graph(session, job=job, report=report, company=company)
    catalyst_links = _catalyst_links_by_report(graph)

    written: list[str] = []
    for company_id in graph.order:
        written.extend(
            await _export_company(
                session,
                writer,
                view=graph.companies[company_id],
                graph=graph,
                catalyst_links=catalyst_links,
                stamp=stamp,
                generator=generator,
            )
        )

    if company is not None:
        subject_title = _company_title(company)
    else:
        # A report with no company row: its peers exported above; the run itself is
        # projected here, with whatever links its own job confirmed.
        subject_title = _company_note_title(request, company_name)
        lone = RunView(
            report=report,
            request=request,
            job=job,
            industry=graph.subject_industry,
            peer_ids=graph.subject_peer_ids,
        )
        written.extend(
            await _export_run(
                session,
                writer,
                run=lone,
                graph=graph,
                company_title=subject_title,
                company_name=company_name,
                catalyst_links=catalyst_links,
                fallback_stamp=stamp,
                generator=generator,
            )
        )
        company_relative = f"10-Companies/{_safe(subject_title)}.md"
        writer.regenerate(
            company_relative,
            _lone_company_generated(
                request,
                report,
                company_name=company_name,
                graph=graph,
                stamp=stamp,
                generator=generator,
            ),
        )
        written.append(company_relative)

    written.extend(_write_catalyst_notes(writer, graph, stamp=stamp, generator=generator))
    written.extend(_write_industry_notes(writer, graph, stamp=stamp, generator=generator))
    written.extend(_write_theme_notes(writer, graph, stamp=stamp, generator=generator))

    current_titles = {_company_title(view.company) for view in graph.companies.values()}
    current_titles.add(subject_title)
    moc_relative = "00-Meta/MOC-Companies.md"
    writer.regenerate(moc_relative, await _moc_generated(session, current_titles))
    written.append(moc_relative)

    readme_relative = "00-Meta/README-generated.md"
    writer.write(readme_relative, _README)
    written.append(readme_relative)

    record = ObsidianExport(
        report_id=report.id,
        exported_at=datetime.now(UTC),
        files=list(dict.fromkeys(written)),
        generator_version=generator,
    )
    session.add(record)
    await session.flush()

    _log.info(
        "obsidian.exported",
        report_id=str(report.id),
        files=len(record.files),
        companies=len(graph.companies),
        vault=str(writer.root),
    )
    return record


# -- The component, company by company ---------------------------------------------------------


async def _export_company(
    session: AsyncSession,
    writer: VaultWriter,
    *,
    view: CompanyView,
    graph: LinkGraph,
    catalyst_links: dict[uuid.UUID, list[str]],
    stamp: datetime,
    generator: str,
) -> list[str]:
    """Every approved run of one company, then its evergreen note."""
    written: list[str] = []
    title = _company_title(view.company)
    for run in view.runs:
        written.extend(
            await _export_run(
                session,
                writer,
                run=run,
                graph=graph,
                company_title=title,
                company_name=view.company.name,
                catalyst_links=catalyst_links,
                fallback_stamp=stamp,
                generator=generator,
            )
        )

    company_relative = f"10-Companies/{_safe(title)}.md"
    writer.regenerate(
        company_relative, _company_generated(view, graph=graph, stamp=stamp, generator=generator)
    )
    written.append(company_relative)
    return written


async def _export_run(
    session: AsyncSession,
    writer: VaultWriter,
    *,
    run: RunView,
    graph: LinkGraph,
    company_title: str,
    company_name: str,
    catalyst_links: dict[uuid.UUID, list[str]],
    fallback_stamp: datetime,
    generator: str,
) -> list[str]:
    """One run note and its source notes, dated by that run's own approval."""
    run_stamp = (run.report.approved_at or fallback_stamp).astimezone(UTC)
    sources = await _sources_for(session, job_id=run.report.job_id)
    claims = await _supported_claims(session, job_id=run.report.job_id)
    written, source_links = _write_source_notes(
        writer, sources, request=run.request, stamp=run_stamp, generator=generator
    )
    custom_sections = await _custom_sections(session, job_id=run.report.job_id)

    run_meta = RunNoteMeta(
        aer_id=f"run-{run.report.id}",
        generated_at=run_stamp,
        generator=generator,
        tags=["aer/run", "aer/approved", f"market/{run.request.exchange.lower()}"],
        report_id=str(run.report.id),
        job_id=str(run.job.id),
        workflow_version=run.job.workflow_version,
        company=company_name,
        ticker=run.request.ticker,
        exchange=run.request.exchange,
        as_of_date=run.request.work_order.as_of_date,
        base_currency=run.request.base_currency,
        point_in_time=run.request.work_order.point_in_time,
        rating=run.report.rating,
        confidence=run.report.confidence,
        valuation=_valuation_dict(run.report),
        horizon_months=run.request.investment_horizon_months,
        aliases=[f"{run.request.ticker} {run.request.work_order.as_of_date.isoformat()} research"],
        company_note=f"[[{company_title}]]",
        industry_note=(
            f"[[{_industry_note_title(run.industry)}]]" if run.industry is not None else None
        ),
        competitors=_peer_links(graph, run.peer_ids),
        catalyst_notes=list(catalyst_links.get(run.report.id, [])),
        source_notes=source_links,
        content_hash=run.report.content_hash,
        custom_sections=custom_sections,
    )
    run_relative = f"20-Runs/{_run_note_title(run.request)}.md"
    writer.write(
        run_relative, render_note(run_meta, _run_body(run.report, run.request, claims, sources))
    )
    written.append(run_relative)
    return written


def _peer_links(graph: LinkGraph, peer_ids: tuple[uuid.UUID, ...]) -> list[str]:
    titles = sorted(
        _company_title(graph.companies[peer].company)
        for peer in peer_ids
        if peer in graph.companies
    )
    return [f"[[{title}]]" for title in titles]


def _write_source_notes(
    writer: VaultWriter,
    sources: list[SourceDocument],
    *,
    request: ResearchRequest,
    stamp: datetime,
    generator: str,
) -> tuple[list[str], list[str]]:
    """One note per non-quarantined source. Returns (paths written, wiki links)."""
    written: list[str] = []
    links: list[str] = []
    for source in sources:
        relative = _source_relative(source)
        title = _source_note_title(source)
        links.append(f"[[{title}]]")
        meta = SourceNoteMeta(
            aer_id=f"src-{source.id}",
            generated_at=stamp,
            generator=generator,
            tags=["aer/source"],
            title=source.title or source.url,
            url=source.url,
            publisher=source.publisher,
            provider=source.provider.value,
            source_tier=source.source_tier.value,
            publication_date=source.publication_date,
            retrieved_at=source.retrieved_at,
            artefact_sha256=(source.artefact.sha256 if source.artefact else None),
        )
        body = (
            f"# {title}\n\n"
            f"Archived source of run [[{_run_note_title(request)}]]. The artefact digest "
            "above is the identity of the bytes this run actually read.\n"
        )
        writer.write(relative, render_note(meta, body))
        written.append(relative)
    return written, links


# -- Bodies ------------------------------------------------------------------------------------


def _run_body(
    report: Report,
    request: ResearchRequest,
    claims: list[tuple[Claim, SourceDocument]],
    sources: list[SourceDocument],
) -> str:
    lines = [
        f"# {request.company_name} — {request.work_order.as_of_date.isoformat()}",
        "",
        "The report of record is the archived, hash-addressed document; this note is a "
        "projection of it for the research journal.",
        "",
        "## Claims",
        "",
    ]
    if claims:
        lines.append(
            "Each claim keeps its block reference, so a later note can cite the claim "
            "— and the verifier will still demand primary evidence before it supports "
            "anything new."
        )
        lines.append("")
        for claim, source in claims:
            title = _source_note_title(source)
            lines.append(f"- {claim.text} — [[{title}]] ^claim-{claim.id.hex[:12]}")
    else:
        lines.append("This run recorded no verified numeric or factual claims.")
    lines.extend(["", "## Prior research comparison", ""])
    comparison = _comparison_lines(report)
    lines.extend(comparison)
    lines.extend(
        [
            "",
            "## Sources",
            "",
            *[f"- [[{_source_note_title(source)}]]" for source in sources],
            "",
        ]
    )
    return "\n".join(lines)


def _comparison_lines(report: Report) -> list[str]:
    """The stored prior-research-comparison section, transcribed — never re-judged.

    Read from the report's own frozen content (the section the deterministic builder
    filled during the run), so the exported comparison is exactly what was approved.
    """
    content: dict[str, Any] = dict(report.content or {})
    markdown = str(content.get("markdown", ""))
    heading = "## Prior Research Comparison"
    start = markdown.find(heading)
    if start == -1:
        return ["The approved report carries no prior-research-comparison section."]
    tail = markdown[start + len(heading) :]
    next_heading = re.search(r"\n## ", tail)
    body = tail[: next_heading.start()] if next_heading else tail
    return body.strip().splitlines()


def _company_generated(
    view: CompanyView, *, graph: LinkGraph, stamp: datetime, generator: str
) -> str:
    """The evergreen company note: run history, valuation history, and its relations."""
    company = view.company
    title = _company_title(company)
    run_links = [f"[[{_run_note_title(run.request)}]]" for run in view.runs]
    competitors = _peer_links(graph, view.competitor_ids)
    theme_links = _company_theme_links(graph).get(company.id, [])
    industry_link = (
        f"[[{_industry_note_title(view.industry)}]]" if view.industry is not None else None
    )

    meta = CompanyNoteMeta(
        aer_id=f"company-{_safe(company.ticker)}-{_safe(company.exchange)}",
        generated_at=stamp,
        generator=generator,
        tags=["aer/company"],
        company=company.name,
        ticker=company.ticker,
        exchange=company.exchange,
        run_notes=run_links,
        industry_note=industry_link,
        competitors=competitors,
        themes=theme_links,
    )

    if not view.runs:
        body_lines = [
            f"# {title}",
            "",
            "Named as a comparable in approved research; this platform holds no approved "
            "research of its own on this company yet.",
            "",
        ]
    else:
        latest = view.runs[-1].report
        body_lines = [
            f"# {title}",
            "",
            f"Latest approved view: {latest.rating or 'no view reached'} as of "
            f"{latest.as_of_date.isoformat()}.",
            "",
            "## Approved runs",
            "",
            *[f"- {link}" for link in run_links],
            "",
            "## Valuation history",
            "",
            *_valuation_history_lines(view.runs),
            "",
        ]
    if competitors:
        body_lines.extend(["## Competitors", "", *[f"- {link}" for link in competitors], ""])
    if theme_links:
        body_lines.extend(["## Themes", "", *[f"- {link}" for link in theme_links], ""])
    if view.driver_accuracy:
        # K3: how the confirmed forecast drivers held up, measured against the first
        # filed year after each prior run. Deltas, not verdicts — whether a miss mattered
        # is the reader's judgement, and the recorded calculations live with the runs.
        body_lines.extend(
            [
                "## Assumption accuracy",
                "",
                "Mean absolute delta between each confirmed driver and its first realised "
                "fiscal year, across the measured approved runs.",
                "",
                *[
                    f"- {row.name.replace('_', ' ')}: {row.mean_absolute_delta} over "
                    f"{row.measured} measured run(s)"
                    for row in view.driver_accuracy
                ],
                "",
            ]
        )
    body_lines.extend(
        [
            "Everything below the marker is yours; the platform regenerates only what is above it.",
            "",
        ]
    )
    return render_note(meta, "\n".join(body_lines))


def _valuation_history_lines(runs: tuple[RunView, ...]) -> list[str]:
    """One line per approved run, oldest first — the range as each run recorded it."""
    lines = []
    for run in runs:
        span = report_view(run.report).valuation_range
        lines.append(
            f"- {run.report.as_of_date.isoformat()} — {span} — [[{_run_note_title(run.request)}]]"
        )
    return lines


def _lone_company_generated(
    request: ResearchRequest,
    report: Report,
    *,
    company_name: str,
    graph: LinkGraph,
    stamp: datetime,
    generator: str,
) -> str:
    """The company note for a report with no company row: one run of history."""
    title = _company_note_title(request, company_name)
    run_link = f"[[{_run_note_title(request)}]]"
    competitors = _peer_links(graph, graph.subject_peer_ids)
    meta = CompanyNoteMeta(
        aer_id=f"company-{_safe(request.ticker)}-{_safe(request.exchange)}",
        generated_at=stamp,
        generator=generator,
        tags=["aer/company"],
        company=company_name,
        ticker=request.ticker,
        exchange=request.exchange,
        run_notes=[run_link],
        industry_note=(
            f"[[{_industry_note_title(graph.subject_industry)}]]"
            if graph.subject_industry is not None
            else None
        ),
        competitors=competitors,
    )
    body_lines = [
        f"# {title}",
        "",
        f"Latest approved view: {report.rating or 'no view reached'} as of "
        f"{report.as_of_date.isoformat()}.",
        "",
        "## Approved runs",
        "",
        f"- {run_link}",
        "",
        "## Valuation history",
        "",
        f"- {report.as_of_date.isoformat()} — {report_view(report).valuation_range} — {run_link}",
        "",
    ]
    if competitors:
        body_lines.extend(["## Competitors", "", *[f"- {link}" for link in competitors], ""])
    # No themes block: a membership needs a company row, and this builder exists for the
    # report that has none — `record_confirmed_themes` records nothing for it.
    body_lines.extend(
        [
            "Everything below the marker is yours; the platform regenerates only what is above it.",
            "",
        ]
    )
    return render_note(meta, "\n".join(body_lines))


# -- Catalysts and industries ------------------------------------------------------------------


def _catalyst_links_by_report(graph: LinkGraph) -> dict[uuid.UUID, list[str]]:
    """Which catalyst notes each run note links, in catalyst order."""
    links: dict[uuid.UUID, list[str]] = {}
    for catalyst in graph.catalyst_views:
        link = f"[[{_catalyst_note_title(catalyst.company, catalyst.label)}]]"
        for run, _ in catalyst.proposals:
            bucket = links.setdefault(run.report.id, [])
            if link not in bucket:
                bucket.append(link)
    return links


def _write_catalyst_notes(
    writer: VaultWriter, graph: LinkGraph, *, stamp: datetime, generator: str
) -> list[str]:
    written: list[str] = []
    for catalyst in graph.catalyst_views:
        title = _catalyst_note_title(catalyst.company, catalyst.label)
        resolved = catalyst.resolved_by
        recorded = catalyst.operator_resolution
        if resolved is not None:
            status = "passed"
        elif catalyst.deadline is not None:
            status = "pending"
        else:
            status = "undated"
        meta = CatalystNoteMeta(
            aer_id=f"catalyst-{_safe(catalyst.company.ticker)}-{_safe(catalyst.label)}",
            generated_at=stamp,
            generator=generator,
            tags=["aer/catalyst"],
            company=catalyst.company.name,
            ticker=catalyst.company.ticker,
            label=catalyst.label,
            expected_timing=catalyst.expected_timing,
            deadline=catalyst.deadline,
            status=status,
            thesis_refs=list(catalyst.thesis_refs),
            # The operator's recorded outcome wins the frontmatter field (K4): "occurred"
            # is an answer where a run link is only a boundary. The calendar keeps
            # `status`; only a person's record may claim what happened.
            resolution=(
                f"{recorded.outcome.value}: {recorded.reason}"
                if recorded is not None
                else (f"[[{_run_note_title(resolved.request)}]]" if resolved is not None else None)
            ),
        )
        lines = [f"# {title}", "", "## Thesis references", ""]
        for run, rationale in catalyst.proposals:
            lines.append(
                f"- Proposed by [[{_run_note_title(run.request)}]] "
                f"(as of {run.report.as_of_date.isoformat()}): {rationale}"
            )
        lines.extend(["", "## Resolution", ""])
        if recorded is not None:
            lines.append(
                f"**{recorded.outcome.value.replace('_', ' ').capitalize()}** — "
                f"{recorded.reason} (recorded by {recorded.recorded_by} on "
                f"{recorded.recorded_at.date().isoformat()})."
            )
        elif resolved is not None:
            lines.append(
                f"The stated window ({catalyst.expected_timing}) had closed by the approved "
                f"run [[{_run_note_title(resolved.request)}]], as of "
                f"{resolved.report.as_of_date.isoformat()}. Whether the event played out as "
                "expected is that run's judgement to record, not this note's."
            )
        elif catalyst.deadline is not None:
            lines.append(
                "The stated window is still open at the latest approved as-of date for "
                "this company."
            )
        else:
            lines.append(
                "No calendar date could be read from the stated timing, so this catalyst "
                "cannot resolve by date."
            )
        lines.append("")
        relative = f"50-Catalysts/{title}.md"
        writer.write(relative, render_note(meta, "\n".join(lines)))
        written.append(relative)
    return written


def _write_industry_notes(
    writer: VaultWriter, graph: LinkGraph, *, stamp: datetime, generator: str
) -> list[str]:
    written: list[str] = []
    for key in sorted(graph.industries):
        profile = graph.industries[key]
        members = graph.industry_members.get(key, ())
        links = [f"[[{_company_title(member)}]]" for member in members]
        meta = IndustryNoteMeta(
            aer_id=f"industry-{profile.key}",
            generated_at=stamp,
            generator=generator,
            tags=["aer/industry"],
            sector_key=profile.key,
            label=profile.label,
            companies=links,
        )
        body_lines = [
            f"# {profile.label}",
            "",
            "Companies whose latest approved run confirmed this classification. Membership "
            "is a statement about the research record, never a market taxonomy.",
            "",
            "## Companies",
            "",
        ]
        if links:
            body_lines.extend(f"- {link}" for link in links)
        else:
            body_lines.append(
                "No exported company currently carries this classification as its latest "
                "confirmed view."
            )
        body_lines.append("")
        relative = f"30-Industries/{_industry_note_title(profile)}.md"
        writer.regenerate(relative, render_note(meta, "\n".join(body_lines)))
        written.append(relative)
    return written


def _theme_note_title(view: ThemeView) -> str:
    return _safe(view.label)


def _company_theme_links(graph: LinkGraph) -> dict[uuid.UUID, list[str]]:
    """Theme note links per company, for the company notes' back-link arrays."""
    links: dict[uuid.UUID, list[str]] = {}
    for view in graph.theme_views:
        link = f"[[{_theme_note_title(view)}]]"
        for company_id, _report_id, _rationale in view.members:
            held = links.setdefault(company_id, [])
            if link not in held:
                held.append(link)
    return links


def _write_theme_notes(
    writer: VaultWriter, graph: LinkGraph, *, stamp: datetime, generator: str
) -> list[str]:
    """One evergreen note per confirmed theme with a member in the component (K1).

    Every company and run a theme note links is in the component by construction — theme
    edges join the reachability walk — so closure holds without a special case here.
    """
    written: list[str] = []
    for view in graph.theme_views:
        company_links: list[str] = []
        run_links: list[str] = []
        member_lines: list[str] = []
        for company_id, report_id, rationale in view.members:
            company_view = graph.companies.get(company_id)
            if company_view is None:  # pragma: no cover -- in-component by construction
                continue
            company_link = f"[[{_company_title(company_view.company)}]]"
            if company_link not in company_links:
                company_links.append(company_link)
            run = next((run for run in company_view.runs if run.report.id == report_id), None)
            run_link = f"[[{_run_note_title(run.request)}]]" if run is not None else ""
            if run_link and run_link not in run_links:
                run_links.append(run_link)
            joined = f" (claimed by {run_link})" if run_link else ""
            member_lines.append(f"- {company_link}{joined}: {rationale}")

        meta = ThemeNoteMeta(
            aer_id=f"theme-{view.key}",
            generated_at=stamp,
            generator=generator,
            tags=["aer/theme"],
            theme_key=view.key,
            label=view.label,
            companies=company_links,
            runs=run_links,
        )
        body_lines = [
            f"# {view.label}",
            "",
            "Companies whose approved research claimed membership of this theme, each "
            "confirmed at a gate. A membership is one run's judgement with a person's "
            "agreement — never a market taxonomy.",
            "",
            "## Members",
            "",
            *member_lines,
            "",
        ]
        relative = f"40-Themes/{_theme_note_title(view)}.md"
        writer.regenerate(relative, render_note(meta, "\n".join(body_lines)))
        written.append(relative)
    return written


async def _moc_generated(session: AsyncSession, current_titles: set[str]) -> str:
    """The map of content: every company this vault has been given, alphabetically.

    Recorded exports are database state, so the list unions the companies of every prior
    export with this one — regenerating the map for one company must not drop another
    the vault already holds.
    """
    titles = set(current_titles)
    exported = await session.scalars(
        select(Report).join(ObsidianExport, ObsidianExport.report_id == Report.id).distinct()
    )
    for prior in exported:
        prior_request = await session.get(ResearchRequest, prior.request_id)
        if prior_request is None:  # pragma: no cover -- FK-guaranteed
            continue
        prior_company = (
            await session.get(Company, prior.company_id) if prior.company_id is not None else None
        )
        name = prior_company.name if prior_company is not None else prior_request.company_name
        titles.add(_company_note_title(prior_request, name))

    lines = [
        "# MOC — Companies",
        "",
        "Generated map of content. Companies appear here as they gain approved runs; "
        "your own organisation belongs below the marker.",
        "",
        *[f"- [[{title}]]" for title in sorted(titles)],
        "",
    ]
    return "\n".join(lines) + "\n"


# -- Queries -----------------------------------------------------------------------------------


async def _sources_for(session: AsyncSession, *, job_id: uuid.UUID) -> list[SourceDocument]:
    rows = await session.scalars(
        select(SourceDocument)
        .where(SourceDocument.job_id == job_id, SourceDocument.quarantined.is_(False))
        .options(selectinload(SourceDocument.artefact))
        .order_by(SourceDocument.url)
    )
    return list(rows)


async def _supported_claims(
    session: AsyncSession, *, job_id: uuid.UUID
) -> list[tuple[Claim, SourceDocument]]:
    """Numeric and factual claims with a verified citation, each with one source to link.

    The first verified citation's source, by claim order: the note links a reader to
    evidence, and the claim page in the app remains the place to see all of it.
    """
    rows = list(
        await session.scalars(
            select(Claim)
            .join(ReportSection, ReportSection.id == Claim.report_section_id)
            .where(
                ReportSection.job_id == job_id,
                Claim.kind.in_((ClaimKind.NUMERIC, ClaimKind.FACTUAL)),
            )
            .options(selectinload(Claim.citations))
            .order_by(Claim.created_at, Claim.id)
        )
    )
    found: list[tuple[Claim, SourceDocument]] = []
    for claim in rows:
        verified = [citation for citation in claim.citations if citation.excerpt_verified]
        if not verified:
            continue
        source = await session.get(SourceDocument, verified[0].source_document_id)
        if source is not None:
            found.append((claim, source))
    return found


async def _custom_sections(session: AsyncSession, *, job_id: uuid.UUID) -> list[dict[str, Any]]:
    rows = await session.execute(
        select(ReportSection.section_key, SectionDefinition)
        .join(SectionDefinition, SectionDefinition.id == ReportSection.section_definition_id)
        .where(ReportSection.job_id == job_id, SectionDefinition.origin == "skill")
        .order_by(ReportSection.position)
    )
    return [
        {
            "key": key,
            "skill": f"{key}@{definition.version}",
            "title": definition.title,
            "tags": ["aer/custom-section"],
        }
        for key, definition in rows.tuples()
    ]


# -- Names -------------------------------------------------------------------------------------


def _safe(text: str) -> str:
    return _UNSAFE.sub("-", text).strip()


def _run_note_title(request: ResearchRequest) -> str:
    return f"{request.work_order.as_of_date.isoformat()} {_safe(request.ticker)}"


def _company_note_title(request: ResearchRequest, company_name: str) -> str:
    return f"{_safe(request.ticker)} - {_safe(company_name)}"


def _company_title(company: Company) -> str:
    return f"{_safe(company.ticker)} - {_safe(company.name)}"


def _industry_note_title(profile: SectorProfile) -> str:
    return _safe(profile.label)


def _catalyst_note_title(company: Company, label: str) -> str:
    return f"{_safe(company.ticker)} {_safe(label)[:60].strip()}"


def _source_note_title(source: SourceDocument) -> str:
    digest = source.artefact.sha256[:6] if source.artefact else str(source.id)[:6]
    label = _safe(source.title or source.url)[:60].strip()
    return f"src-{digest} - {label}"


def _source_relative(source: SourceDocument) -> str:
    return f"90-Sources/{_source_note_title(source)}.md"


def _valuation_dict(report: Report) -> dict[str, Any] | None:
    if report.valuation_low is None or report.valuation_high is None:
        return None
    valuation: dict[str, Any] = {
        "low": str(report.valuation_low),
        "high": str(report.valuation_high),
        "currency": report.valuation_currency,
        "per": "share",
    }
    if report.valuation_base is not None:
        valuation["base"] = str(report.valuation_base)
    return valuation
