"""Exporting one approved report into the vault — deterministically, on request.

**Only ``immutable`` reports export** (section 2.8, rule 1): a draft was never agreed to
and a rejected run was declined, so neither may leave a trace in the vault. Nothing
exports automatically; the report page and the CLI both call this, and both only when a
person asked.

**A second export is the first export.** Every note is a function of the database state
and the report's own approval date — no wall clock reaches a byte — so re-exporting an
unchanged report rewrites identical files. What changes between exports is only the
``obsidian_exports`` row recording the act.
"""

from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime
from typing import Any

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from aer.config import Settings
from aer.core.enums import ClaimKind
from aer.db.models import (
    Claim,
    Company,
    Job,
    ObsidianExport,
    Report,
    ReportSection,
    ResearchRequest,
    SectionDefinition,
    SourceDocument,
)
from aer.errors import AerError
from aer.obsidian.notes import (
    CompanyNoteMeta,
    RunNoteMeta,
    SourceNoteMeta,
    render_note,
)
from aer.obsidian.vault import VaultWriter
from aer.services.history import approved_reports_for
from aer.version import version

__all__ = ["ObsidianExportError", "export_report"]

_log = structlog.get_logger("aer.obsidian.export")

# What may appear in a filename. Everything else becomes a hyphen: vault filenames come
# partly from fetched document titles, and a title is data, not a path.
_UNSAFE = re.compile(r"[^A-Za-z0-9 \-_.,()&]")

_README = """# Generated by Ageiantic Equity Research

Everything in this vault outside `99-Personal/` is machine-generated from approved
research runs. The database and the artefact store remain the record; these notes are a
derived, one-directional projection of them.

- Notes are regenerated on export. In evergreen notes (companies, MOC), only the content
  **above** the `AER:END-GENERATED` marker is rewritten; anything you write below a
  marker is yours and survives every regeneration.
- `99-Personal/` is never written by the application.
- Prior research informs hypotheses only. It is never evidence: a claim reused from an
  earlier note must be re-sourced before it can support anything.

This is a personal research tool. Nothing in this vault is regulated investment advice.
"""


class ObsidianExportError(AerError):
    """The report may not export, or the vault is not configured."""

    code = "obsidian_export_refused"


async def export_report(
    session: AsyncSession, *, settings: Settings, report_id: uuid.UUID
) -> ObsidianExport:
    """Project one approved report into the vault and record the act.

    Raises:
        ObsidianExportError: If no vault root is configured, or the report does not
            exist, or it was never approved — rule 1 is checked here, before any path
            is even resolved.
    """
    if settings.obsidian_vault_root is None:
        message = "No Obsidian vault is configured (AER_OBSIDIAN_VAULT_ROOT). Nothing was written."
        raise ObsidianExportError(message)

    report = await session.get(Report, report_id)
    if report is None:
        message = f"No report {report_id}."
        raise ObsidianExportError(message, context={"report_id": str(report_id)})
    if not report.immutable or report.approved_at is None:
        message = (
            "Only approved reports export. This report was never approved, and a draft "
            "must not leave a trace in the vault (section 2.8, rule 1)."
        )
        raise ObsidianExportError(message, context={"report_id": str(report_id)})

    request = await session.get(ResearchRequest, report.request_id)
    job = await session.get(Job, report.job_id)
    if request is None or job is None:  # pragma: no cover -- FK-guaranteed rows
        message = f"Report {report_id} has lost its request or job."
        raise ObsidianExportError(message, context={"report_id": str(report_id)})
    company = (
        await session.get(Company, report.company_id) if report.company_id is not None else None
    )
    company_name = company.name if company is not None else request.company_name

    writer = VaultWriter(
        settings.obsidian_vault_root, personal_root=settings.obsidian_personal_root
    )

    stamp = report.approved_at.astimezone(UTC)
    generator = f"ageiantic-aer@{version()}"
    sources = await _sources_for(session, job_id=job.id)
    claims = await _supported_claims(session, job_id=job.id)

    written, source_links = _write_source_notes(
        writer, sources, request=request, stamp=stamp, generator=generator
    )
    company_title = _company_note_title(request, company_name)

    custom_sections = await _custom_sections(session, job_id=job.id)
    run_meta = RunNoteMeta(
        aer_id=f"run-{report.id}",
        generated_at=stamp,
        generator=generator,
        tags=["aer/run", "aer/approved", f"market/{request.exchange.lower()}"],
        report_id=str(report.id),
        job_id=str(job.id),
        workflow_version=job.workflow_version,
        company=company_name,
        ticker=request.ticker,
        exchange=request.exchange,
        as_of_date=request.as_of_date,
        base_currency=request.base_currency,
        point_in_time=request.point_in_time,
        rating=report.rating,
        confidence=report.confidence,
        valuation=_valuation_dict(report),
        horizon_months=request.investment_horizon_months,
        aliases=[f"{request.ticker} {request.as_of_date.isoformat()} research"],
        company_note=f"[[{company_title}]]",
        source_notes=source_links,
        content_hash=report.content_hash,
        custom_sections=custom_sections,
    )
    run_relative = f"20-Runs/{request.as_of_date.isoformat()} {_safe(request.ticker)}.md"
    writer.write(run_relative, render_note(run_meta, _run_body(report, request, claims, sources)))
    written.append(run_relative)

    company_relative = f"10-Companies/{_safe(company_title)}.md"
    company_generated = await _company_generated(
        session,
        report=report,
        request=request,
        company=company,
        company_name=company_name,
        company_title=company_title,
        stamp=stamp,
        generator=generator,
    )
    writer.regenerate(company_relative, company_generated)
    written.append(company_relative)

    moc_relative = "00-Meta/MOC-Companies.md"
    writer.regenerate(moc_relative, _moc_generated(company_title))
    written.append(moc_relative)

    readme_relative = "00-Meta/README-generated.md"
    writer.write(readme_relative, _README)
    written.append(readme_relative)

    record = ObsidianExport(
        report_id=report.id,
        exported_at=datetime.now(UTC),
        files=written,
        generator_version=generator,
    )
    session.add(record)
    await session.flush()

    _log.info(
        "obsidian.exported",
        report_id=str(report.id),
        files=len(written),
        vault=str(writer.root),
    )
    return record


def _write_source_notes(
    writer: VaultWriter,
    sources: list[SourceDocument],
    *,
    request: ResearchRequest,
    stamp: datetime,
    generator: str,
) -> tuple[list[str], list[str]]:
    """One note per non-quarantined source. Returns (paths written, wiki links)."""
    written: list[str] = []
    links: list[str] = []
    for source in sources:
        relative = _source_relative(source)
        title = _source_note_title(source)
        links.append(f"[[{title}]]")
        meta = SourceNoteMeta(
            aer_id=f"src-{source.id}",
            generated_at=stamp,
            generator=generator,
            tags=["aer/source"],
            title=source.title or source.url,
            url=source.url,
            publisher=source.publisher,
            provider=source.provider.value,
            source_tier=source.source_tier.value,
            publication_date=source.publication_date,
            retrieved_at=source.retrieved_at,
            artefact_sha256=(source.artefact.sha256 if source.artefact else None),
        )
        body = (
            f"# {title}\n\n"
            f"Archived source of run [[{_run_note_title(request)}]]. The artefact digest "
            "above is the identity of the bytes this run actually read.\n"
        )
        writer.write(relative, render_note(meta, body))
        written.append(relative)
    return written, links


# -- Bodies ------------------------------------------------------------------------------------


def _run_body(
    report: Report,
    request: ResearchRequest,
    claims: list[tuple[Claim, SourceDocument]],
    sources: list[SourceDocument],
) -> str:
    lines = [
        f"# {request.company_name} — {request.as_of_date.isoformat()}",
        "",
        "The report of record is the archived, hash-addressed document; this note is a "
        "projection of it for the research journal.",
        "",
        "## Claims",
        "",
    ]
    if claims:
        lines.append(
            "Each claim keeps its block reference, so a later note can cite the claim "
            "— and the verifier will still demand primary evidence before it supports "
            "anything new."
        )
        lines.append("")
        for claim, source in claims:
            title = _source_note_title(source)
            lines.append(f"- {claim.text} — [[{title}]] ^claim-{claim.id.hex[:12]}")
    else:
        lines.append("This run recorded no verified numeric or factual claims.")
    lines.extend(["", "## Prior research comparison", ""])
    comparison = _comparison_lines(report)
    lines.extend(comparison)
    lines.extend(
        [
            "",
            "## Sources",
            "",
            *[f"- [[{_source_note_title(source)}]]" for source in sources],
            "",
        ]
    )
    return "\n".join(lines)


def _comparison_lines(report: Report) -> list[str]:
    """The stored prior-research-comparison section, transcribed — never re-judged.

    Read from the report's own frozen content (the section the deterministic builder
    filled during the run), so the exported comparison is exactly what was approved.
    """
    content: dict[str, Any] = dict(report.content or {})
    markdown = str(content.get("markdown", ""))
    heading = "## Prior Research Comparison"
    start = markdown.find(heading)
    if start == -1:
        return ["The approved report carries no prior-research-comparison section."]
    tail = markdown[start + len(heading) :]
    next_heading = re.search(r"\n## ", tail)
    body = tail[: next_heading.start()] if next_heading else tail
    return body.strip().splitlines()


async def _company_generated(
    session: AsyncSession,
    *,
    report: Report,
    request: ResearchRequest,
    company: Company | None,
    company_name: str,
    company_title: str,
    stamp: datetime,
    generator: str,
) -> str:
    run_links: list[str] = []
    if company is not None:
        for prior in reversed(await approved_reports_for(session, company_id=company.id)):
            prior_request = await session.get(ResearchRequest, prior.request_id)
            if prior_request is not None:
                run_links.append(f"[[{_run_note_title(prior_request)}]]")
    if not run_links:
        run_links.append(f"[[{_run_note_title(request)}]]")

    meta = CompanyNoteMeta(
        aer_id=f"company-{_safe(request.ticker)}-{_safe(request.exchange)}",
        generated_at=stamp,
        generator=generator,
        tags=["aer/company"],
        company=company_name,
        ticker=request.ticker,
        exchange=request.exchange,
        run_notes=run_links,
    )
    body_lines = [
        f"# {company_title}",
        "",
        f"Latest approved view: {report.rating or 'no view reached'} as of "
        f"{report.as_of_date.isoformat()}.",
        "",
        "## Approved runs",
        "",
        *[f"- {link}" for link in run_links],
        "",
        "Everything below the marker is yours; the platform regenerates only what is above it.",
        "",
    ]
    return render_note(meta, "\n".join(body_lines))


def _moc_generated(company_title: str) -> str:
    return (
        "# MOC — Companies\n\n"
        "Generated map of content. Companies appear here as they gain approved runs; "
        "your own organisation belongs below the marker.\n\n"
        f"- [[{company_title}]]\n\n"
    )


# -- Queries -----------------------------------------------------------------------------------


async def _sources_for(session: AsyncSession, *, job_id: uuid.UUID) -> list[SourceDocument]:
    rows = await session.scalars(
        select(SourceDocument)
        .where(SourceDocument.job_id == job_id, SourceDocument.quarantined.is_(False))
        .options(selectinload(SourceDocument.artefact))
        .order_by(SourceDocument.url)
    )
    return list(rows)


async def _supported_claims(
    session: AsyncSession, *, job_id: uuid.UUID
) -> list[tuple[Claim, SourceDocument]]:
    """Numeric and factual claims with a verified citation, each with one source to link.

    The first verified citation's source, by claim order: the note links a reader to
    evidence, and the claim page in the app remains the place to see all of it.
    """
    rows = list(
        await session.scalars(
            select(Claim)
            .join(ReportSection, ReportSection.id == Claim.report_section_id)
            .where(
                ReportSection.job_id == job_id,
                Claim.kind.in_((ClaimKind.NUMERIC, ClaimKind.FACTUAL)),
            )
            .options(selectinload(Claim.citations))
            .order_by(Claim.created_at, Claim.id)
        )
    )
    found: list[tuple[Claim, SourceDocument]] = []
    for claim in rows:
        verified = [citation for citation in claim.citations if citation.excerpt_verified]
        if not verified:
            continue
        source = await session.get(SourceDocument, verified[0].source_document_id)
        if source is not None:
            found.append((claim, source))
    return found


async def _custom_sections(session: AsyncSession, *, job_id: uuid.UUID) -> list[dict[str, Any]]:
    rows = await session.execute(
        select(ReportSection.section_key, SectionDefinition)
        .join(SectionDefinition, SectionDefinition.id == ReportSection.section_definition_id)
        .where(ReportSection.job_id == job_id, SectionDefinition.origin == "skill")
        .order_by(ReportSection.position)
    )
    return [
        {
            "key": key,
            "skill": f"{key}@{definition.version}",
            "title": definition.title,
            "tags": ["aer/custom-section"],
        }
        for key, definition in rows.tuples()
    ]


# -- Names -------------------------------------------------------------------------------------


def _safe(text: str) -> str:
    return _UNSAFE.sub("-", text).strip()


def _run_note_title(request: ResearchRequest) -> str:
    return f"{request.as_of_date.isoformat()} {_safe(request.ticker)}"


def _company_note_title(request: ResearchRequest, company_name: str) -> str:
    return f"{_safe(request.ticker)} - {_safe(company_name)}"


def _source_note_title(source: SourceDocument) -> str:
    digest = source.artefact.sha256[:6] if source.artefact else str(source.id)[:6]
    label = _safe(source.title or source.url)[:60].strip()
    return f"src-{digest} - {label}"


def _source_relative(source: SourceDocument) -> str:
    return f"90-Sources/{_source_note_title(source)}.md"


def _valuation_dict(report: Report) -> dict[str, Any] | None:
    if report.valuation_low is None or report.valuation_high is None:
        return None
    valuation: dict[str, Any] = {
        "low": str(report.valuation_low),
        "high": str(report.valuation_high),
        "currency": report.valuation_currency,
        "per": "share",
    }
    if report.valuation_base is not None:
        valuation["base"] = str(report.valuation_base)
    return valuation
