"""Shared column type aliases.

Declared once so that "money is Decimal" and "timestamps carry a timezone" are properties
of the schema rather than things each model author has to remember. A naive timestamp or a
float money column would each be a silent correctness bug in an auditable research
system, and neither would fail loudly at the point it was introduced.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Annotated, Any

from sqlalchemy import BigInteger, DateTime, Numeric, String, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import mapped_column

__all__ = [
    "BigIntPk",
    "Cost",
    "Json",
    "JsonList",
    "Money",
    "Sha256",
    "Timestamp",
    "TimestampOptional",
    "UuidFk",
    "UuidFkOptional",
    "UuidPk",
]

# Generated by the database, not the application: an INSERT that bypasses the ORM still
# gets a valid id, and ids stay unguessable.
UuidPk = Annotated[
    uuid.UUID,
    mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    ),
]

# Foreign-key columns. Deliberately separate from UuidPk: reusing the primary-key alias
# on an FK column carries its `server_default=gen_random_uuid()` across, so an INSERT that
# omitted the FK would silently generate a random dangling id instead of failing loudly.
UuidFk = Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True))]
UuidFkOptional = Annotated[uuid.UUID | None, mapped_column(UUID(as_uuid=True))]

# audit_events is append-only and high-volume, and its ordering is the chain order, so a
# monotonic integer key is both cheaper and more meaningful than a UUID here.
BigIntPk = Annotated[int, mapped_column(BigInteger, primary_key=True, autoincrement=True)]

# The DTZ lint rules stop naive datetimes reaching the database from Python; these stop
# them being representable in the schema at all.
Timestamp = Annotated[datetime, mapped_column(DateTime(timezone=True))]
TimestampOptional = Annotated[datetime | None, mapped_column(DateTime(timezone=True))]

# Money and rates are Decimal, never float. Binary floating point cannot represent 0.1
# exactly, and a research platform that silently rounds cash flows is worthless.
# Money: user-facing amounts. Cost: metered spend, which needs sub-penny resolution
# because a single model call can cost a fraction of a penny and they must sum accurately.
Money = Annotated[Decimal, mapped_column(Numeric(10, 2))]
Cost = Annotated[Decimal, mapped_column(Numeric(10, 4))]

# A hex-encoded SHA-256 digest is always exactly 64 characters; the fixed width makes a
# truncated or malformed hash a database error rather than a silent mismatch later.
Sha256 = Annotated[str, mapped_column(String(64))]

Json = Annotated[dict[str, Any], mapped_column(JSONB)]
JsonList = Annotated[list[Any], mapped_column(JSONB)]
